### ISSUE TITLE
Login time is inaccurate

### ISSUE THREAD

**Issue by Murky-MoMo** [Ayeven/discord-musicbot#1]
Hi!
so in your `ready.js`, you use: 
```const moment = require ('moment');
const time = moment().format("YYYY MM DD HH:mm:ss");
module.exports = {
  run(client) {
    console.log(`Logged in as ${client.user.tag} at ${time}`);
  }
}
```
 The problem with this is that requiring it will run the code before the exports and so, "_time_" isn't the accurate time of when your bot logged in, it's the time of when you required this file
other than the fact that this is inaccurate, it could also lead to issues should you want to re-login for some reason or calculate the latency
So i suggest generating the time inside the `run` function like so 
```
module.exports = {
  run(client) {
    const moment = require ('moment');
    const time = moment().format("YYYY MM DD HH:mm:ss");
    console.log(`Logged in as ${client.user.tag} at ${time}`);
  }
}
```
Now on a side note there are other things I would like to talk about, like how there's no direction on what "config" should be, what values it should have

Also instead of looping through `fs.readdirSync` i suggest using `glob` or `fast-glob`, which I'll add a pr for shortly with a list on why it would be better :)

**Comment by Ayeven** [comment]
Merged, and closed

**Comment by Murky-MoMo** [comment]
That PR doesn't deal with the config issue I mentioned. You can however specify JSON Schemas! And this should tell the users what they need to add on a config.json
I have been waiting to try this feature out, after I'm done with it, there will probably be another pull request
Also if you have any questions regarding these changes, I'd be happy to explain since this is for both of us to learn.
